version: 3
metadata_directory: metadata
services:
  mailhog:
    port: 8025
  hasura:
    environment:
      hasura_graphql_enable_remote_schema_permissions: false
    image: hasura/graphql-engine:v2.10.1
  auth:
    image: nhost/hasura-auth:0.13.2
  storage:
    image: nhost/hasura-storage:0.2.4
auth:
  access_control:
    email:
      allowed_email_domains: ''
      allowed_emails: ''
      blocked_email_domains: ''
      blocked_emails: ''
    allowed_redirect_urls: ''
  anonymous_users:
    enabled: true
  client_url: http://localhost:3000
  disable_new_users: false
  email:
    passwordless:
      enabled: true
    signin_email_verified_required: true
    template:
      fetch_url: ''
  gravatar:
    default: ''
    enabled: true
    rating: ''
  locale:
    allowed_locales: en
    default: en
  password:
    hibp:
      enabled: false
    min_length: 3
  provider:
    apple:
      enabled: false
      client_id: ''
      key_id: ''
      private_key: ''
      scope: name,email
      team_id: ''
    bitbucket:
      enabled: false
      client_id: ''
      client_secret: ''
    facebook:
      enabled: false
      client_id: ''
      client_secret: ''
      scope: email,photos,displayName
    github:
      enabled: false
      client_id: ''
      client_secret: ''
      scope: user:email
      token_url: ''
      user_profile_url: ''
    gitlab:
      enabled: false
      base_url: ''
      client_id: ''
      client_secret: ''
      scope: read_user
    google:
      enabled: false
      client_id: ''
      client_secret: ''
      scope: email,profile
    linkedin:
      enabled: false
      client_id: ''
      client_secret: ''
      scope: r_emailaddress,r_liteprofile
    spotify:
      enabled: false
      client_id: ''
      client_secret: ''
      scope: user-read-email,user-read-private
    strava:
      enabled: false
      client_id: ''
      client_secret: ''
    twilio:
      enabled: false
      account_sid: ''
      auth_token: ''
      messaging_service_id: ''
    twitter:
      enabled: false
      consumer_key: ''
      consumer_secret: ''
    windows_live:
      enabled: false
      client_id: ''
      client_secret: ''
      scope: wl.basic,wl.emails,wl.contacts_emails
  sms:
    passwordless:
      enabled: false
    provider: null
    twilio:
      account_sid: ''
      auth_token: ''
      from: ''
      messaging_service_id: ''
  smtp:
    host: nhost_mailhog
    method: ''
    pass: password
    port: 1025
    secure: false
    sender: hasura-auth@example.com
    user: user
  access_token:
    expires_in: 900
  refresh_token:
    expires_in: 43200
  user:
    default_allowed_roles: user,me
    default_role: user
  mfa:
    enabled: true
    totp_issuer: nhost
